### ISSUE TITLE
Error in cumulative cases

### ISSUE THREAD

**Issue by benflips** [vipinbhatnagar/covid19#1]
Andhra Pradesh and Assam both have large (>25%) drops in cumulative infections

**Comment by vipinbhatnagar** [comment]
This happened due to reordering the states alphabetically in second week of April. Today's files have this fixed.

**Comment by benflips** [comment]
Thanks @vipinbhatnagar

**Comment by benflips** [comment]
I'll have Andhra Pradesh and Assam online in 20 minutes.
