### ISSUE TITLE
Cumulative infected cases for many regions showing greater than 25% reduction in total cases 

### ISSUE THREAD

**Issue by benflips** [vipinbhatnagar/covid19#4]
The following regions have cumulative case numbers that have decreased in the last few days.  Suspect there might be a re-ordering of data on the government website?

   Country.Region   Province.State checkI checkD
2           India   Andhra Pradesh  FALSE   TRUE
5           India            Bihar  FALSE   TRUE
6           India       Chandigarh  FALSE   TRUE
9           India            Delhi  FALSE   TRUE
11          India          Gujarat  FALSE   TRUE
12          India          Haryana  FALSE   TRUE
13          India Himachal Pradesh  FALSE   TRUE
14          India  Jammu & Kashmir  FALSE   TRUE
15          India       Jharkhanda  FALSE   TRUE
16          India        Karnataka  FALSE   TRUE
17          India           Kerela  FALSE   TRUE
19          India   Madhya Pradesh  FALSE   TRUE
20          India      Maharashtra  FALSE   TRUE
25          India           Odisha  FALSE   TRUE
27          India           Punjab  FALSE   TRUE
28          India        Rajasthan  FALSE   TRUE
30          India       Tamil Nadu  FALSE   TRUE
31          India        Telangana  FALSE   TRUE
32          India          Tripura  FALSE   TRUE
34          India    Uttar Pradesh  FALSE   TRUE
35          India      West Bengal  FALSE   TRUE

**Comment by vipinbhatnagar** [comment]
There were problems with entries for 30th and 31st of May, these are corrected now manually. The scrapping is picking up the correct column now from govt. website (as they added a new column & total number of confirmed cases are moved to the new column on the website). Thanks Ben for noticing and informing us. Thanks Jyoti for fixing it quickly.
